apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service 
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - image: okteto.dev/backend
        name: backend
        env:
            - name : RABBITMQ_URL 
              value : amqp://rabbitmq
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    dev.okteto.com/auto-ingress: "domain"
spec:
  type: ClusterIP  
  ports:
  - name: "backend-service"
    port: 5000
  selector:
    app: backend-service 